DROP SEQUENCE MYNOSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE MYNOSEQ;

CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYTITLE VARCHAR2(2000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL,
	READCOUNT NUMBER NOT NULL,
	MYBOARDPW VARCHAR2(30)
);

ALTER TABLE MYBOARD ADD FILEUPDOWN VARCHAR2(1000);

INSERT INTO MYBOARD
VALUES(MYNOSEQ.NEXTVAL, '1234', '1234', '1234', SYSDATE, 0, 0);

INSERT INTO MYBOARD
VALUES(MYNOSEQ.NEXTVAL, '1234', '2222', '33333', SYSDATE, 0, 0);

UPDATE MYBOARD SET FILEUPDOWN = 'BLANK';

SELECT * FROM MYBOARD ORDER BY MYNO DESC;