DROP SEQUENCE ADDNOSEQ;
DROP TABLE ADDRESS;

CREATE SEQUENCE ADDNOSEQ;

CREATE TABLE ADDRESS(
	ADDNO NUMBER PRIMARY KEY,
	USERID VARCHAR2(100),
	ADDRESS VARCHAR2(100),
	POSTNUM NUMBER,
	PHONE VARCHAR2(100),
	ORIADD CHAR
);