DROP SEQUENCE ADDNOSEQ;
DROP TABLE ADDRESS;

CREATE SEQUENCE ADDNOSEQ;

CREATE TABLE ADDRESS(
	ADDNO NUMBER PRIMARY KEY,
	USERID VARCHAR2(100),
	ADDRESS VARCHAR2(100),
	POSTNUM NUMBER,
	PHONE VARCHAR2(100),
	ORIADD CHAR
);



DROP SEQUENCE ADDRNOSEQ;
DROP TABLE ADDR;

CREATE SEQUENCE ADDRNOSEQ;

CREATE TABLE ADDR(
	ADDRNO NUMBER PRIMARY KEY,
	ADDNAME VARCHAR2(100),
	USERNAME VARCHAR2(1000),
	ADDRESS_1 VARCHAR2(1000),
	ADDRESS_2 VARCHAR2(1000),
	ADDNO VARCHAR2(100),
	MAINADDR CHAR
);

INSERT INTO ADDR
VALUES(ADDRNOSEQ.NEXTVAL, '기본주소', '테스터', '회사 건물', '404호', '12345', 'N');

SELECT ADDRNO, ADDNAME , USERNAME, ADDRESS_1, ADDRESS_2, ADDNO, MAINADDR
		FROM ADDR
		WHERE USERNAME = '테스터' AND ADDNAME = '기본주소' 

UPDATE ADDR
SET MAINADDR = 'N'
WHERE ADDRNO = 4

SELECT * FROM ADDR;
