DROP SEQUENCE CARTNOSEQ;
DROP TABLE CART;

CREATE SEQUENCE CARTNOSEQ;

CREATE TABLE CART(
	CARTNO NUMBER PRIMARY KEY,
	PRONO NUMBER,
	PROTITLE VARCHAR2(100),
	PROKATE_1 VARCHAR2(100),
	PROKATE_2 VARCHAR2(100),
	USERNAME VARCHAR2(100),
	AMOUNT NUMBER
);



DROP SEQUENCE CARTNOSEQ;
DROP TABLE CART;

CREATE SEQUENCE CARTNOSEQ;

CREATE TABLE CART(
	CARTNO NUMBER PRIMARY KEY,
	PRONO NUMBER,
	PRONAME VARCHAR2(100),
	PROTITLE VARCHAR2(100),
	PROKATE_1 VARCHAR2(100),
	PROKATE_2 VARCHAR2(100),
	USERNAME VARCHAR2(100),
	AMOUNT NUMBER
	
);

INSERT INTO CART
VALUES(CARTNOSEQ.NEXTVAL, 2, '테스트' ,'메로나', '음식', '아이스크림', '테스터', 1)

DELETE FROM CART
WHERE CARTNO = 9;

SELECT * FROM CART
ORDER BY CARTNO DESC;
