DROP SEQUENCE DELNOSEQ;
DROP TABLE DELIVERY;

CREATE SEQUENCE DELNOSEQ;

CREATE TABLE DELIVERY(
	DELNO NUMBER PRIMARY KEY,
	PROTITLE VARCHAR2(100),
	AMOUT NUMBER,
	ORDPRICE NUMBER,
	USERNAME VARCHAR2(100),
	DELSTATE VARCHAR2(100),
	DELDATE VARCHAR2(100)
);



DROP SEQUENCE DELNOSEQ;
DROP TABLE DELIVERY;

CREATE SEQUENCE DELNOSEQ;

CREATE TABLE DELIVERY(
	DELNO VARCHAR2(100) PRIMARY KEY,
	PROTITLE VARCHAR2(100),
	PROAMOUT NUMBER,
	TOTAL NUMBER,
	USERNAME VARCHAR2(100),
	DELSTATE VARCHAR2(100),
	DELDATE VARCHAR2(100)
);
ALTER TABLE DELIVERY ADD ADDRESS_1 VARCHAR2(1000);
ALTER TABLE DELIVERY ADD ADDRESS_2 VARCHAR2(1000);

INSERT INTO DELIVERY 
VALUES(('DEL'||TO_CHAR(SYSDATE, 'YYMMDD')||LPAD(DELNOSEQ.NEXTVAL, 5, '0')), '메로나', 1, 1000, '실험', '결제확인 중', SYSDATE);

INSERT INTO DELIVERY
		VALUES(('DEL'||TO_CHAR(SYSDATE, 'YYMMDD')||LPAD(ORDNOSEQ.NEXTVAL, 5, '0')), '메로나' ,10, 1000, 'name', '준비중입니다', TO_CHAR(SYSDATE, 'YY-MM-DD'))

SELECT MAX(DELNO) FROM DELIVERY

SELECT * FROM DELIVERY;
SELECT * FROM DELIVERY
WHERE USERNAME = '테스터'

DELETE FROM DELIVERY
WHERE DELNO = 'DEL21082000008'

SELECT COUNT(DELNO), SUM(TOTAL)
		FROM DELIVERY
		WHERE USERNAME = '테스터'