DROP SEQUENCE ORDERNOSEQ;
DROP TABLE ORDERCART;

CREATE SEQUENCE ORDERNOSEQ;

CREATE TABLE ORDERCART(
	ORDNO VARCHAR2(100) PRIMARY KEY,
	PRONO NUMBER,
	PROTITLE VARCHAR2(100),
	ORDPRICE NUMBER,
	PRINCIPAL NUMBER,
	TAX NUMBER,
	USERNAME VARCHAR2(100),
	ORDERDATE DATE
);



DROP SEQUENCE ORDNOSEQ;
DROP TABLE ORDERCART;

CREATE SEQUENCE ORDNOSEQ;

CREATE TABLE ORDERCART(
	ORDNO VARCHAR2(100) PRIMARY KEY,
	DELNO VARCHAR2(100),
	PRONO NUMBER,
	PROTITLE VARCHAR2(100),
	PRONAME VARCHAR2(100),
	AMOUT NUMBER,
	ORDPRICE NUMBER,
	PRINCIPAL NUMBER,
	TAX NUMBER,
	USERNAME VARCHAR2(100),
	ORDDATE VARCHAR2(100)
);

SELECT * FROM ORDERCART
WHERE USERNAME = '테스터';

SELECT TO_DATE(TO_CHAR(PRODATE, 'YYMMDD'))
FROM PRODUCT



SELECT * FROM PRODUCT ORDER BY PRONO DESC

UPDATE PRODUCT SET ORDPRICE = '1000' , PRINCIPAL = '1000' , TAX = '10'
WHERE PRONO = '23'

INSERT INTO ORDERCART
		VALUES(('ORD'||TO_CHAR(SYSDATE, 'YYMMDD')||LPAD(ORDNOSEQ.NEXTVAL, 5, '0')), 0 , 5 , '옥동자', '테스트', 1000, 1000, 10,
		'테스터' ,TO_CHAR(SYSDATE, 'YYMMDD'))
		
INSERT INTO ORDERCART
		VALUES(ORDNOSEQ.NEXTVAL, 5 , '옥동자', '테스트', 1000, 1000, 10,
		'테스터' ,SYSDATE)