DROP SEQUENCE ORDHISNOSEQ;
DROP TABLE ORDHISTORY;

CREATE SEQUENCE ORDHISNOSEQ;

CREATE TABLE ORDHISTORY(
	ORDHISNO NUMBER PRIMARY KEY,
	USERNAME NUMBER,
	DELNO VARCHAR2(100),
	REASON VARCHAR2(1000),
	ORDHISDATE DATE
);


DROP SEQUENCE ORDHISNOSEQ;
DROP TABLE ORDHISTORY;

CREATE SEQUENCE ORDHISNOSEQ;

CREATE TABLE ORDHISTORY(
	ORDHISNO NUMBER PRIMARY KEY,
	USERNAME VARCHAR2(100),
	DELNO VARCHAR2(100),
	REASON VARCHAR2(1000),
	ORDHISDATE VARCHAR2(100)
);

INSERT INTO ORDHISTORY
VALUES(ORDHISNOSEQ.NEXTVAL, '테스터', 'DEL21082000010', '옥동자 외 2개의 상품을 주문하셨습니다.', TO_CHAR(SYSDATE, 'YY-MM-DD'))

SELECT ORDHISNO, USERNAME, DELNO, REASON, ORDHISDATE FROM ORDHISTORY
WHERE USERNAME = '테스터'
ORDER BY ORDHISNO DESC