DROP SEQUENCE MYUSERSEQ;
DROP TABLE MYUSER;

CREATE SEQUENCE MYUSERSEQ;

CREATE TABLE MYUSER(
	USERNO NUMBER,
	USERID VARCHAR2(1000) NOT NULL,
	USERPW VARCHAR2(1000) NOT NULL,
	USERNAME VARCHAR2(1000) PRIMARY KEY NOT NULL
);

INSERT INTO MYUSER
VALUES(MYUSERSEQ.NEXTVAL, 'user', '1234', 'USER');



DROP SEQUENCE MYUSERSEQ;
DROP TABLE MYUSER;

CREATE SEQUENCE MYUSERSEQ;

CREATE TABLE MYUSER(
	USERNO NUMBER PRIMARY KEY,
	USERID VARCHAR2(1000),
	USERPW VARCHAR2(1000),
	USERNAME VARCHAR2(1000),
	USERROLE VARCHAR2(100),
	ADDRESS_1 VARCHAR2(1000),
	ADDRESS_2 VARCHAR2(1000),
	ADDNO VARCHAR2(100),
	USERDATE DATE
	
);

INSERT INTO MYUSER
VALUES(MYUSERSEQ.NEXTVAL, 'test', '1234', '테스터', 'ADMIN', '회사 건물', '404호', '12345', SYSDATE);

DELETE FROM MYUSER WHERE USERNO = 2

SELECT * FROM MYUSER
