DROP SEQUENCE FREECOMMENTSEQ;
DROP TABLE FREECOMMENT;

CREATE SEQUENCE FREECOMMENTSEQ

CREATE TABLE FREECOMMENT(
	FREECOMSEQ NUMBER NOT NULL,
	FREECOMBOARDSEQ NUMBER NOT NULL,
	FREECOMNICKNAME VARCHAR2(100),
	FREECOMREGDATE DATE NOT NULL,
	FREECOMPARENT NUMBER,
	FREECOMCONTENT VARCHAR2(1000) NOT NULL,
	CONSTRAINT FREECOMMENT_PK PRIMARY KEY (FREECOMSEQ),
	CONSTRAINT FREECOMMENT_FK FOREIGN KEY (FREECOMBOARDSEQ) REFERENCES FREEBOARD (BOARDSEQ)
);