DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;

--글번호 ,그룹번호,그룹순서,제목공백, 삭제여부("Y,N")
--제목 ,내용 ,작성자 ,작성일

CREATE TABLE ANSWERBOARD(
		BOARDNO NUMBER NOT NULL,
		GROUPNO NUMBER NOT NULL,
		GROUPSEQ NUMBER NOT NULL,
		TITLETAB NUMBER NOT NULL,
		DELFLAG VARCHAR2(2) NOT NULL,
		TITLE VARCHAR2(1000) NOT NULL,
		CONTENT VARCHAR2(4000) NOT NULL,
	 	WRITER VARCHAR2(500) NOT NULL,
		REGDATE DATE NOT NULL,
		--제약조건 1: BOARDNO에 ANSWER_BOARDNO_PK라는 이름으로 PK걸자
		CONSTRAINT ANSWER_BOARD_PK PRIMARY KEY(BOARDNO),
		--제약조건 2: DELFLAG에 ANSWER_DELFLAGE_CK라는 이름으로 CHECK 걸자('Y,N')
		CONSTRAINT ANSWER_DELFLAG_CK CHECK(DELFLAG IN ('Y','N'))
	
);

--1번글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL,GROUPNOSEQ.NEXTVAL,1,0,'N','답변형 그럼~','아니다','우빈',SYSDATE);

--1번글에 답글
--update
--부모의 그룹번호와 같은 그룹이면서
--부모의 그룹순서보다 더 큰 긇들의
--그룹순서 +1
UPDATE ANSWERBOARD
SET GROUPSEQ =GROUPSEQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1);
--INSERT
INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=1)+1,
	(SELECT TITLETAB +1 FROM ANSWERBOARD WHERE BOARDNO=1),
	'N',
	'RE:답변형 어렵다',
	'진짜 쉽지않다',
	'울프',
	SYSDATE
);

--1번글 삭제
UPDATE ANSWERBOARD
SET DELFLAG = 'Y'
WHERE BOARDNO =1;


SELECT BOARDNO,GROUPNO,GROUPSEQ,TITLETAB,DELFLAG,TITLE,CONTENT,WRITER,REGDATE
FROM ANSWERBOARD
ORDER BY GROUPNO DESC,GROUPSEQ;














































