DROP SEQUENCE CARTNOSEQ;
DROP TABLE CART;

CREATE SEQUENCE CARTNOSEQ;

CREATE TABLE CART(
	CARTNO NUMBER PRIMARY KEY,
	PRONO NUMBER,
	PROTITLE VARCHAR2(100),
	PROKATE_1 VARCHAR2(100),
	PROKATE_2 VARCHAR2(100),
	USERNAME VARCHAR2(100),
	AMOUNT NUMBER
);