DROP SEQUENCE DELNOSEQ;
DROP TABLE DELIVERY;

CREATE SEQUENCE DELNOSEQ;

CREATE TABLE DELIVERY(
	DELNO NUMBER PRIMARY KEY,
	PROTITLE VARCHAR2(100),
	AMOUT NUMBER,
	ORDPRICE NUMBER,
	USERNAME VARCHAR2(100),
	DELSTATE VARCHAR2(100),
	DELDATE VARCHAR2(100)
);

