DROP SEQUENCE ORDERNOSEQ;
DROP TABLE ORDERCART;

CREATE SEQUENCE ORDERNOSEQ;

CREATE TABLE ORDERCART(
	ORDNO VARCHAR2(100) PRIMARY KEY,
	PRONO NUMBER,
	PROTITLE VARCHAR2(100),
	ORDPRICE NUMBER,
	PRINCIPAL NUMBER,
	TAX NUMBER,
	USERNAME VARCHAR2(100),
	ORDERDATE DATE
);