DROP SEQUENCE ORDHISNOSEQ;
DROP TABLE ORDHISTORY;

CREATE SEQUENCE ORDHISNOSEQ;

CREATE TABLE ORDHISTORY(
	ORDHISNO NUMBER PRIMARY KEY,
	USERNAME NUMBER,
	DELNO VARCHAR2(100),
	REASON VARCHAR2(1000),
	ORDHISDATE DATE
);