DROP SEQUENCE MYUSERSEQ;
DROP TABLE MYUSER;

CREATE SEQUENCE MYUSERSEQ;

CREATE TABLE MYUSER(
	USERNO NUMBER,
	USERID VARCHAR2(1000) NOT NULL,
	USERPW VARCHAR2(1000) NOT NULL,
	USERNAME VARCHAR2(1000) PRIMARY KEY NOT NULL
);

INSERT INTO MYUSER
VALUES(MYUSERSEQ.NEXTVAL, 'user', '1234', 'USER');

