DROP SEQUENCE COMMENTSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE CBOARD;

CREATE SEQUENCE COMMENTNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;

CREATE TABLE CBOARD(
	COMMENTNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER,
	GROUPSEQ NUMBER,
	TITLETAB NUMBER,
	MYNO NUMBER,
	USERNAME VARCHAR2(30),
	CCONTENT VARCHAR2(1000) NOT NULL,
	CDATE DATE
);

INSERT INTO CBOARD
VALUES(COMMENTNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, 1, 'test', 'test', SYSDATE);

UPDATE COMMENTBOARD
SET GROUPSEQ = GROUPSEQ + 1
WHERE GROUPNO = (SELECT GROUPNO FROM COMMENTBOARD WHERE COMMENTNO = 1)
AND GROUPSEQ > (SELECT GROUPSEQ FROM COMMENTBOARD WHERE COMMENTNO = 1);


INSERT INTO COMMENTBOARD
VALUES(
		COMMENTNOSEQ.NEXTVAL,
		(SELECT COMMENTNO FROM COMMENTBOARD WHERE COMMENTNO = 2),
		(SELECT GROUPSEQ FROM COMMENTBOARD WHERE COMMENTNO = 2) + 1,
		(SELECT TITLETAB +1 FROM COMMENTBOARD WHERE COMMENTNO = 2),
		1,
		'test1',
		'test',
		SYSDATE
);